server:
  port: 8005

management:
  port: 8990

info:
  component: Turbine

spring:
  application:
    name: WIZIQ-TURBINE

  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.17.175:8002/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: false
    metadataMap:
      hostname: ${vcap.application.application_uris[0]}
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}