server:
  port: 8002

info:
  name: Discovery-Server
  discription: Discovery Server

spring:
  application:
    name: DISCOVERY-SERVER
  cloud:
    config:
      uri:  http://192.168.17.175:8001/


logging:
  file: /var/log/wiziq/infrastucture/EurekaServer.log

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.17.175:8002/eureka/
