server:
  port: 8002
  address: localhost
  
#logging:
#  file: /var/log/wiziq/infrastucture/EurekaServer.log

eureka:
  instance:
    hostname: localhost
    waitTimeInMsWhenSyncEmpty: 0
    preferIpAddress: false
  server:
    enable-self-preservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
      defaultZone: http://localhost:8002/eureka/