

module.exports = Object.freeze({
	HEADER: "HEADER",
	COURSE_LIST: "COURSE_LIST",
	COURSE_DETAIL: "COURSE_DETAIL",
	CLASS_LIST: "CLASS_LIST",
	CLASS_DETAIL: "CLASS_DETAIL",
	CLASS_DETAIL_META: "CLASS_DETAIL_META",
	DISCOVER: "DISCOVER",
	DISCOVER_BANNER: "DISCOVER_BANNER",
	FOOTER: "FOOTER",
	MOBILE_HEAD: "MOBILE_HEAD",
	MOBILE_BODY: "MOBILE_BODY",
	CONTACT_US: "CONTACT_US",
	SIGN_IN: "SIGN_IN",
	SIGN_UP: "SIGN_UP"
});