info:
  component: Turbine

management:
  port: 8006

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

#turbine:
#  appConfig: customers,stores,productapi
#  clusterNameExpression: 'default'

#turbine:
#  aggregator:
#    clusterConfig: CUSTOMERS
#  appConfig: customers