server:
  port: 8001

spring:
  application:
    name: CONFIG-SERVICE
  profiles:
    active: native

info:
  name: Config Server
  description: This is config server

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8002/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: false
    metadataMap:
      hostname: ${vcap.application.application_uris[0]}
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

logging:
  file: /var/log/wiziq/infrastucture/ConfigServer.log
